/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GaslessVoting } from "./GaslessVoting";

export { GaslessVoting__factory } from "./factories/GaslessVoting__factory";
