/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ITaskTreasuryUpgradableInterface extends utils.Interface {
  functions: {
    "depositFunds(address,address,uint256)": FunctionFragment;
    "getCreditTokensByUser(address)": FunctionFragment;
    "getTotalCreditTokensByUser(address)": FunctionFragment;
    "getWhitelistedServices()": FunctionFragment;
    "totalUserTokenBalance(address,address)": FunctionFragment;
    "updateMaxFee(uint256)": FunctionFragment;
    "updateWhitelistedService(address,bool)": FunctionFragment;
    "useFunds(address,address,uint256)": FunctionFragment;
    "userTokenBalance(address,address)": FunctionFragment;
    "withdrawFunds(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositFunds",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditTokensByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCreditTokensByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistedServices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUserTokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelistedService",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "useFunds",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditTokensByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCreditTokensByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistedServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUserTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelistedService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;

  events: {
    "FundsDeposited(address,address,uint256)": EventFragment;
    "FundsWithdrawn(address,address,address,uint256)": EventFragment;
    "LogDeductFees(address,address,address,uint256,address)": EventFragment;
    "UpdatedMaxFee(uint256)": EventFragment;
    "UpdatedService(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundsDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogDeductFees"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedMaxFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatedService"): EventFragment;
}

export type FundsDepositedEvent = TypedEvent<
  [string, string, BigNumber],
  { sender: string; token: string; amount: BigNumber }
>;

export type FundsDepositedEventFilter = TypedEventFilter<FundsDepositedEvent>;

export type FundsWithdrawnEvent = TypedEvent<
  [string, string, string, BigNumber],
  { receiver: string; initiator: string; token: string; amount: BigNumber }
>;

export type FundsWithdrawnEventFilter = TypedEventFilter<FundsWithdrawnEvent>;

export type LogDeductFeesEvent = TypedEvent<
  [string, string, string, BigNumber, string],
  {
    user: string;
    executor: string;
    token: string;
    fees: BigNumber;
    service: string;
  }
>;

export type LogDeductFeesEventFilter = TypedEventFilter<LogDeductFeesEvent>;

export type UpdatedMaxFeeEvent = TypedEvent<[BigNumber], { maxFee: BigNumber }>;

export type UpdatedMaxFeeEventFilter = TypedEventFilter<UpdatedMaxFeeEvent>;

export type UpdatedServiceEvent = TypedEvent<
  [string, boolean],
  { service: string; add: boolean }
>;

export type UpdatedServiceEventFilter = TypedEventFilter<UpdatedServiceEvent>;

export interface ITaskTreasuryUpgradable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITaskTreasuryUpgradableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getTotalCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getWhitelistedServices(overrides?: CallOverrides): Promise<[string[]]>;

    totalUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    updateMaxFee(
      _newMaxFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateWhitelistedService(
      service: string,
      isWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    useFunds(
      user: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositFunds(
    receiver: string,
    token: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCreditTokensByUser(
    user: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTotalCreditTokensByUser(
    user: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getWhitelistedServices(overrides?: CallOverrides): Promise<string[]>;

  totalUserTokenBalance(
    user: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateMaxFee(
    _newMaxFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateWhitelistedService(
    service: string,
    isWhitelist: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  useFunds(
    user: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userTokenBalance(
    user: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawFunds(
    receiver: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTotalCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getWhitelistedServices(overrides?: CallOverrides): Promise<string[]>;

    totalUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateMaxFee(
      _newMaxFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateWhitelistedService(
      service: string,
      isWhitelist: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    useFunds(
      user: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "FundsDeposited(address,address,uint256)"(
      sender?: string | null,
      token?: string | null,
      amount?: BigNumberish | null
    ): FundsDepositedEventFilter;
    FundsDeposited(
      sender?: string | null,
      token?: string | null,
      amount?: BigNumberish | null
    ): FundsDepositedEventFilter;

    "FundsWithdrawn(address,address,address,uint256)"(
      receiver?: string | null,
      initiator?: string | null,
      token?: string | null,
      amount?: null
    ): FundsWithdrawnEventFilter;
    FundsWithdrawn(
      receiver?: string | null,
      initiator?: string | null,
      token?: string | null,
      amount?: null
    ): FundsWithdrawnEventFilter;

    "LogDeductFees(address,address,address,uint256,address)"(
      user?: string | null,
      executor?: string | null,
      token?: string | null,
      fees?: null,
      service?: null
    ): LogDeductFeesEventFilter;
    LogDeductFees(
      user?: string | null,
      executor?: string | null,
      token?: string | null,
      fees?: null,
      service?: null
    ): LogDeductFeesEventFilter;

    "UpdatedMaxFee(uint256)"(
      maxFee?: BigNumberish | null
    ): UpdatedMaxFeeEventFilter;
    UpdatedMaxFee(maxFee?: BigNumberish | null): UpdatedMaxFeeEventFilter;

    "UpdatedService(address,bool)"(
      service?: string | null,
      add?: null
    ): UpdatedServiceEventFilter;
    UpdatedService(
      service?: string | null,
      add?: null
    ): UpdatedServiceEventFilter;
  };

  estimateGas: {
    depositFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhitelistedServices(overrides?: CallOverrides): Promise<BigNumber>;

    totalUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateMaxFee(
      _newMaxFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateWhitelistedService(
      service: string,
      isWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    useFunds(
      user: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalCreditTokensByUser(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhitelistedServices(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateMaxFee(
      _newMaxFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateWhitelistedService(
      service: string,
      isWhitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    useFunds(
      user: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawFunds(
      receiver: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
