/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { GaslessVoting, GaslessVotingInterface } from "../GaslessVoting";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220347f004a0dd5081481f1b2ecfdf1875ceddf0c1f14a4fe50c9b059d6277e995064736f6c63430008040033";

type GaslessVotingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GaslessVotingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GaslessVoting__factory extends ContractFactory {
  constructor(...args: GaslessVotingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GaslessVoting> {
    return super.deploy(overrides || {}) as Promise<GaslessVoting>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): GaslessVoting {
    return super.attach(address) as GaslessVoting;
  }
  connect(signer: Signer): GaslessVoting__factory {
    return super.connect(signer) as GaslessVoting__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GaslessVotingInterface {
    return new utils.Interface(_abi) as GaslessVotingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GaslessVoting {
    return new Contract(address, _abi, signerOrProvider) as GaslessVoting;
  }
}
